config/routes.rb
Rails.application.routes.draw do
  resources :products do
    resources :sales, only: %i[create show]
  end
  resources :sales, only: %i[index]
  devise_for :users
  root to: 'pages#home'
  get '/mystyle', to: 'products#mystyle'
  get '/mybusiness', to: 'sales#mybusiness'
  get '/merci', to: 'pages#merci'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :owner, class_name: "User"
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  CATEGORY = %w[slow smooth fast hard]

  validates :name, presence: true, null: false
  validates :description, presence: true, null: false
  validates :category, presence: true, inclusion: { in: CATEGORY }
  validates :photo, presence: true, null: false
  validates :price, presence: true, null: false

  mount_uploader :photo, PhotoUploader

end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :product
  belongs_to :user



  validates :product_id, presence: true
  validates :user_id, presence: true
  validates :date, presence: true
  validates :paid, presence: true
  after_initialize :init

  def init
    self.paid = false
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
  has_many :sales, through: :products
  has_many :buys, class_name: 'Sale', foreign_key: :user_id
  has_many :own_products, class_name: 'Product', foreign_key: :owner_id

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :address, presence: true
  validates :avatar, presence: true

  mount_uploader :avatar, AvatarUploader

  after_initialize :init

  def initsh
    self.seller = false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name address avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name address avatar])
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show destroy]
  skip_before_action :authenticate_user!, only: %i[show index]
  def new
    @product = Product.new
    authorize(@product)
  end

  def create
    @product = Product.new(product_params)
    @product.owner = current_user
    authorize(@product)
    if @product.save
      redirect_to mystyle_path
    else
      p @product.errors
      render 'new'
    end
  end

  def index
    # @product = Product.find(params[:id])
    @products = policy_scope(Product)
  end

  def show
    @sale = Sale.new
    @product = Product.find(params[:id])
    @markers =
      {
        lat: @product.latitude,
        lng: @product.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { product: @product })
      }
  end

  def mystyle
    @products = Product.where(owner: current_user)
    authorize(@products)
  end

  def edit
  end

  def destroy
  end

  def update
  end
end


private

  def set_product
    @product = Product.find(params[:id])
    authorize(@product)
  end

  def product_params
    params.require(:product).permit(:name, :description, :category, :photo, :price, :active, :address)
  end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_product, only: %i[show destroy]

  def create

    @product = Product.find(params[:product_id])
    authorize(@product)
    @sale = Sale.new
    @sale.product = @product
    @sale.user = current_user
    @sale.date = params[:date]

    if @sale.save
      redirect_to merci_path
    else
      raise
      p @sale.errors
      render product_path(@product)
    end
  end

  def index
    @sales = Sale.all.where(user: current_user)
    @products = policy_scope(Product)
  end

  def mybusiness
    @sales = Sale.all.where(user: current_user)
    @products = policy_scope(Product)
  end

  def show
  end

  private

  def set_product
    @product = Product.find(params[:id])
    authorize(@product)
  end

  def sales_params
    params.require(:sales).permit(:product_id, :date, :paid, params[:sale])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dead Style</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <div class="navbar_push">
    </div>

    <div class="wrapper">
      <%= yield %>
      <%= javascript_include_tag 'application' %>
      <%= javascript_pack_tag 'application' %>
    </div>

    <div class="footer_push">
    </div>
        <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

<!-- section of the 4 sections -->
<div class="section4">
  <div class="homecard">
    <%= link_to "slow", products_path %>
  </div>
  <div class="homecard">
    <%= link_to "smooth", products_path %>
  </div>
  <div class="homecard">
    <%= link_to "fast", products_path %>
  </div>
  <div class="homecard">
    <%= link_to "hard", products_path %>
  </div>

</div>

<!-- section of the all -->
<div class="homeall">
  <%= link_to "All the style", products_path %>
</div>

app/views/products/_info_window.html.erb
<h2><%= product.name %></h2>
<p><%= product.address %></p>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<h1 class="h1title">Choose your style</h1>

<div class="h1title pt-2 pb-4">
  <%= render 'shared/search_bar' %>
</div>

<div class="indexpro">
  <% @products.each do |product| %>
    <%= link_to product_path(product) do %>
      <div class="indexcard">
        <%= product.name %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/products/mystyle.html.erb
<div class="container">
  <div class="showproducts row">
    <% @products.each do |product| %>
      <%= link_to product_path(product) do %>
        <div class="col-md-auto showproduct" >
          <div class="infos">
            <h2><%= product.name %></h2>
            <%= product.description %>
          </div>
          <%= cl_image_tag(product.photo) %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<h1>Propose your style</h1>

<%= simple_form_for @product do |f| %>
  <%= f.input :name, autofocus: true %>
  <%= f.input :category, collection: Product::CATEGORY, selected: :first%>
  <%= f.input :description %>
  <%= f.input :address, input_html: { id: "address"}%>
  <%= f.input :price %>
  <%= f.input :active %>
  <%= f.input :photo %>

  <%= f.button :submit %>
<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>


<div class="container">
  <div class="showproducts row">

        <div class="col-6" >
          <%= cl_image_tag @product.photo %>

        </div>
        <div class="col-6"
            id="map"
            style="width: 100%;
            height: 600px;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
          ></div>
        </div>
        <div class="w-100"></div>
        <div class="col-6" >
          <%= @product.description %>
          <%= @product.category %>

          <%= @product.rating %>
        </div>
        <div class="col-6" >
          <%= @product.price %>
          <%= @product.active %>

          <%= simple_form_for @sale,:url => product_sales_path(@product), :method => :post do |f| %>
            <%= f.input :date, autofocus: true, as: :date, html5: true%>

            <%= f.button :submit %>
          <% end %>
          <%= link_to 'I want to try', product_sales_path(@product), method: :post %>
        </div>

  </div>
</div>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>

app/views/sales/create.html.erb
<h1>Sales#create</h1>
<p>Find me in app/views/sales/create.html.erb</p>

app/views/sales/index.html.erb
<div class="container">
  <div class="showproducts row">
    <% @sales.each do |sale| %>
      <%= link_to sales_path(sale) do %>
        <div class="col-md-auto showproduct" >
          <div class="infos">
            <h2><%= sale.date %></h2>
            <%= sale.paid %>
          </div>
           <%= cl_image_tag(sale.product.photo) %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/sales/show.html.erb
<h1>Sales#show</h1>
<p>Find me in app/views/sales/show.html.erb</p>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.0),rgba(0,0,0,0.0)), url(https://res.cloudinary.com/jcjp971/image/upload/v1566500495/deadstyle/banner_skxjci.png);">
  <div class="container">
   <!--  <h1>Le Wagon brings <strong>tech skills</strong> to <strong>creative people</strong>!</h1>
    <p>Change your life and learn to code at one of our campuses around the world.</p>
    <a class="btn btn-flat" href="#">Apply now</a> -->
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fas fa-book-dead"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fas fa-biohazard"></i></a>
    <a href="#"><i class="fas fa-skull-crossbones"></i></a>
  </div>
  <div class="footer-copyright">
    <i class="fas fa-bomb"></i> Life is better with a bomb <i class="fas fa-bomb"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to "/", class: "navbar-brand" do %>
    <%= cl_image_tag("https://res.cloudinary.com/jcjp971/image/upload/v1566500495/deadstyle/logo_moooko.jpg") %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% histoires = ["https://res.cloudinary.com/jcjp971/image/upload/v1566500497/deadstyle/histoire2_mywhlu.jpg","https://res.cloudinary.com/jcjp971/image/upload/v1566500498/deadstyle/histoire1_b7smw5.jpg","https://res.cloudinary.com/jcjp971/image/upload/v1566500498/deadstyle/histoire3_plty31.jpg"]%>

      <li class="nav-item dropdown tips">
        <%= image_tag "https://res.cloudinary.com/jcjp971/image/upload/v1566500494/deadstyle/tips_qubnxb.png", height: '32', class: "dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-center" aria-labelledby="navbarDropdown">
          <%= image_tag(histoires.sample, height: '480') %>
        </div>
      </li>

    </ul>
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item active">
        <%= link_to "Propose your style", new_product_path, class: "nav-link" %>
      </li>

      <% if current_user %>

        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>

            <% if current_user.own_products.count > 0 %>
              <%= link_to "Show my styles", mystyle_path, class: "dropdown-item" %>
              <%= link_to "My business", sales_path, class: "dropdown-item" %>
            <% end %>


            <%= link_to "See my death", sales_path, class: "dropdown-item" %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>



    </ul>
  </div>
</div>

app/views/shared/_search_bar.html.erb
<div class="searchbar">
  <%= form_with(url: "/products", method: :get) do %>
    <%= select_tag(:category, options_for_select(Product::CATEGORY)) %>
    <%= submit_tag("resultat") %>
  <% end %>
</div>